[package]
name = "asm_testing"
version = "0.1.0"
edition = "2021"

include = [
    "src/**",
    "build.rs",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.83"
